services:
  database:
    image: "postgres:16.4-alpine3.20"
    container_name: "postgresql-db"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USERNAME"]
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_DATABASE}"
    networks:
      - "main"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./database/data:/var/lib/postgresql/data"
      - "./database/initdb:/docker-entrypoint-initdb.d"

networks:
  main:
    name: "databases-net"
