services:
  database:
    image: "postgres:15.4-bullseye"
    container_name: "postgresql-db"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $SQL_USER"]
    environment:
      - "POSTGRES_USER=${SQL_USER}"
      - "POSTGRES_PASSWORD=${SQL_PSWD}"
      - "POSTGRES_DB=${SQL_DATABASE}"
    networks:
      - "main"
    ports:
      - "${SQL_PORT}:5432"
    volumes:
      - "./database/data:/var/lib/postgresql/data"
      - "./database/initdb:/docker-entrypoint-initdb.d"

networks:
  main:
    name: "databases-net"
