services:
  database:
    image: "mongo:7.0.14"
    container_name: "mongo-db"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"]
    environment:
      - "MONGODB_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PSWD}"
      - "MONGODB_INITDB_DATABASE=${MONGO_DATABASE}"
    networks:
      - "main"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "./database/data:/data/db"
      - "./database/initdb:/docker-entrypoint-initdb.d"

networks:
  main:
    name: "databases-net"
